import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { GeneratedSchemaMetadata, GeneratedSchemaSnapshot, SchemaSnapshot } from "./model.js";
import { SCHEMA_FORMAT_VERSION } from "./model.js";

export interface GenerateSchemaOptions {
  readonly outDir: string;
  readonly typePolicy?: unknown;
  readonly generatorVersion?: string;
  readonly dialectVersion?: string;
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (typeof value !== "object" || value === null) return value;
  return Object.fromEntries(
    Object.entries(value)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, item]) => [key, canonicalize(item)]),
  );
}

const hash = (value: unknown): string =>
  createHash("sha256")
    .update(JSON.stringify(canonicalize(value)))
    .digest("hex");

export function calculateSchemaHash(schema: SchemaSnapshot): string {
  return hash(schema);
}

export function calculateTypePolicyHash(policy: unknown): string {
  return hash(policy);
}

export interface SchemaDriftResult {
  readonly drifted: boolean;
  readonly schemaChanged: boolean;
  readonly typePolicyChanged: boolean;
  readonly expectedSchemaHash: string;
  readonly actualSchemaHash: string;
  readonly expectedTypePolicyHash: string;
  readonly actualTypePolicyHash: string;
}

export function checkSchemaDrift(
  generated: GeneratedSchemaSnapshot,
  current: SchemaSnapshot,
  policy: unknown = {},
): SchemaDriftResult {
  const comparableCurrent: SchemaSnapshot = {
    ...current,
    ...(generated.formatVersion === undefined ? {} : { formatVersion: generated.formatVersion }),
    ...(generated.dialectVersion === undefined ? {} : { dialectVersion: generated.dialectVersion }),
  };
  const actualSchemaHash = calculateSchemaHash(comparableCurrent);
  const actualTypePolicyHash = calculateTypePolicyHash(policy);
  const schemaChanged = generated.metadata.schemaHash !== actualSchemaHash;
  const typePolicyChanged = generated.metadata.typePolicyHash !== actualTypePolicyHash;
  return {
    drifted: schemaChanged || typePolicyChanged,
    schemaChanged,
    typePolicyChanged,
    expectedSchemaHash: generated.metadata.schemaHash,
    actualSchemaHash,
    expectedTypePolicyHash: generated.metadata.typePolicyHash,
    actualTypePolicyHash,
  };
}

export async function generateSchemaPackage(
  schema: SchemaSnapshot,
  options: GenerateSchemaOptions,
): Promise<GeneratedSchemaMetadata> {
  const policy = options.typePolicy ?? {};
  const versionedSchema: SchemaSnapshot = {
    ...schema,
    formatVersion: SCHEMA_FORMAT_VERSION,
    ...(options.dialectVersion === undefined ? {} : { dialectVersion: options.dialectVersion }),
  };
  const metadata: GeneratedSchemaMetadata = {
    generatorVersion: options.generatorVersion ?? "1.0.0",
    schemaHash: calculateSchemaHash(versionedSchema),
    typePolicyHash: calculateTypePolicyHash(policy),
  };
  await mkdir(options.outDir, { recursive: true });
  await writeFile(
    join(options.outDir, "schema.json"),
    `${JSON.stringify({ ...versionedSchema, metadata }, null, 2)}\n`,
    "utf8",
  );
  const moduleSource = [
    `// Generated by @typed-sql/cli ${metadata.generatorVersion}. Schema metadata only; do not edit.`,
    `export const schema = ${JSON.stringify(versionedSchema, null, 2)} as const;`,
    `export const metadata = ${JSON.stringify(metadata, null, 2)} as const;`,
    "export type DatabaseSchema = typeof schema;",
    "",
  ].join("\n");
  await writeFile(join(options.outDir, "index.ts"), moduleSource, "utf8");
  return metadata;
}

export type { GeneratedSchemaMetadata } from "./model.js";
