import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { GeneratedSchemaMetadata, GeneratedSchemaSnapshot, SchemaSnapshot, TypePolicy } from "./model.js";
import { defaultPostgresTypePolicy } from "./model.js";

export interface GenerateSchemaOptions {
  readonly outDir: string;
  readonly typePolicy?: TypePolicy;
  readonly generatorVersion?: string;
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (typeof value !== "object" || value === null) return value;
  return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonicalize(item)]));
}

const hash = (value: unknown): string => createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");

export function calculateSchemaHash(schema: SchemaSnapshot): string {
  return hash(schema);
}

export function calculateTypePolicyHash(policy: TypePolicy): string {
  return hash(policy);
}

export interface SchemaDriftResult {
  readonly drifted: boolean;
  readonly schemaChanged: boolean;
  readonly typePolicyChanged: boolean;
  readonly expectedSchemaHash: string;
  readonly actualSchemaHash: string;
  readonly expectedTypePolicyHash: string;
  readonly actualTypePolicyHash: string;
}

export function checkSchemaDrift(generated: GeneratedSchemaSnapshot, current: SchemaSnapshot, policy: TypePolicy = defaultPostgresTypePolicy): SchemaDriftResult {
  const actualSchemaHash = calculateSchemaHash(current);
  const actualTypePolicyHash = calculateTypePolicyHash(policy);
  const schemaChanged = generated.metadata.schemaHash !== actualSchemaHash;
  const typePolicyChanged = generated.metadata.typePolicyHash !== actualTypePolicyHash;
  return {
    drifted: schemaChanged || typePolicyChanged,
    schemaChanged,
    typePolicyChanged,
    expectedSchemaHash: generated.metadata.schemaHash,
    actualSchemaHash,
    expectedTypePolicyHash: generated.metadata.typePolicyHash,
    actualTypePolicyHash,
  };
}

export async function generateSchemaPackage(schema: SchemaSnapshot, options: GenerateSchemaOptions): Promise<GeneratedSchemaMetadata> {
  const policy = options.typePolicy ?? defaultPostgresTypePolicy;
  const metadata: GeneratedSchemaMetadata = {
    generatorVersion: options.generatorVersion ?? "0.0.0",
    schemaHash: calculateSchemaHash(schema),
    typePolicyHash: calculateTypePolicyHash(policy),
  };
  await mkdir(options.outDir, { recursive: true });
  await writeFile(join(options.outDir, "schema.json"), `${JSON.stringify({ ...schema, metadata }, null, 2)}\n`, "utf8");
  const moduleSource = [
    `// Generated by @typed-sql/cli ${metadata.generatorVersion}. Do not edit.`,
    'import { createPostgresDatabase as createRuntimePostgresDatabase } from "@typed-sql/runtime";',
    'import type { PostgresDatabase, PostgresDatabaseOptions } from "@typed-sql/runtime";',
    `export const schema = ${JSON.stringify(schema, null, 2)} as const;`,
    `export const metadata = ${JSON.stringify(metadata, null, 2)} as const;`,
    `export const typePolicy = ${JSON.stringify(policy, null, 2)} as const;`,
    "export type DatabaseSchema = typeof schema;",
    "export function createGeneratedDatabase(options: Omit<PostgresDatabaseOptions, \"typePolicy\">): PostgresDatabase {",
    "  return createRuntimePostgresDatabase({ ...options, typePolicy });",
    "}",
    'export { sql, createDatabase, createPostgresDatabase } from "@typed-sql/runtime";',
    "",
  ].join("\n");
  await writeFile(join(options.outDir, "index.ts"), moduleSource, "utf8");
  return metadata;
}

export type { GeneratedSchemaMetadata } from "./model.js";
