export const diagnosticRegistry = Object.freeze({
  TSQ001: { category: "syntax", summary: "SQL syntax could not be parsed." },
  TSQ002: { category: "resource", summary: "SQL exceeded a parser resource limit." },
  TSQ003: { category: "resource", summary: "Conditional SQL exceeded the structural variant limit." },
  TSQ004: { category: "contract", summary: "Structural SQL requires an explicitly trusted fragment." },
  TSQ005: { category: "support", summary: "Runtime SQL cannot be analyzed statically." },
  TSQ007: { category: "contract", summary: "The schema snapshot and dialect do not match." },
  TSQ100: { category: "schema", summary: "A referenced table does not exist." },
  TSQ101: { category: "schema", summary: "A referenced column does not exist." },
  TSQ102: { category: "schema", summary: "A column reference is ambiguous." },
  TSQ103: { category: "schema", summary: "A relation alias or qualified column is unknown." },
  TSQ104: { category: "result", summary: "A result expression needs an explicit output name." },
  TSQ105: { category: "result", summary: "Two result columns produce the same property name." },
  TSQ106: { category: "type", summary: "A cast target is invalid or unknown." },
  TSQ107: { category: "schema", summary: "An unqualified table name is ambiguous." },
  TSQ108: { category: "schema", summary: "A relation alias is duplicated." },
  TSQ202: { category: "type", summary: "A function is unknown." },
  TSQ203: { category: "type", summary: "An operator cannot be inferred safely." },
  TSQ204: { category: "type", summary: "A function overload is ambiguous." },
  TSQ205: { category: "type", summary: "A composed parameter has incompatible structural contexts." },
  TSQ210: { category: "support", summary: "Recursive CTE inference is not supported safely." },
  TSQ211: { category: "schema", summary: "A CTE name is duplicated." },
  TSQ212: { category: "result", summary: "A CTE does not return rows." },
  TSQ213: { category: "result", summary: "A CTE column list has the wrong arity." },
  TSQ214: { category: "result", summary: "INSERT source and target arities differ." },
  TSQ215: { category: "schema", summary: "A JOIN USING column is not unique on both sides." },
  TSQ216: { category: "result", summary: "A scalar subquery does not return exactly one column." },
  TSQ217: { category: "result", summary: "An IN subquery does not return exactly one column." },
  TSQ218: { category: "schema", summary: "A statement writes to a column that is not writable." },
  TSQ219: { category: "schema", summary: "An INSERT omits a required target column." },
  TSQ220: { category: "syntax", summary: "A recursive CTE has an invalid member shape." },
  TSQ221: { category: "support", summary: "A recursive CTE member uses a prohibited aggregate or window function." },
  TSQ222: { category: "schema", summary: "A named or framed window definition is invalid." },
  TSQ223: { category: "syntax", summary: "A window-function invocation uses a prohibited modifier." },
  TSQ224: { category: "syntax", summary: "A conflict-handling clause is structurally ambiguous or invalid." },
  TSQ225: { category: "support", summary: "A data-modification result expression uses an unavailable source." },
  TSQ226: { category: "schema", summary: "A conflict target does not match a unique constraint." },
  TSQ227: { category: "syntax", summary: "A built-in function invocation has an invalid shape." },
  TSQ228: { category: "semantic", summary: "A grouped or clause-scoped expression is invalid." },
  TSQ301: { category: "drift", summary: "The live schema or type policy differs from the generated snapshot." },
  TSQ401: { category: "support", summary: "The dialect surface is intentionally unsupported." },
  TSQ402: { category: "support", summary: "Exact analysis requires normalized server evidence." },
  TSQ403: { category: "support", summary: "The recorded server version is outside the supported range." },
  TSQ404: { category: "support", summary: "The SQL feature is newer than the recorded server version." },
  TSQ405: { category: "support", summary: "The SQL feature was removed before the recorded server version." },
  TSQ406: { category: "support", summary: "A required server feature, setting, or declaration is absent." },
  TSQ407: { category: "support", summary: "Recorded server settings make SQL behavior ambiguous." },
  TSQ500: { category: "verification", summary: "Live database metadata differs from compiler evidence." },
  TSQ501: { category: "verification", summary: "A query could not be verified safely or statically." },
  TSQ502: { category: "verification", summary: "Native live verification failed without persisting driver details." },
} as const);

export type TypedSqlDiagnosticCode = keyof typeof diagnosticRegistry;

export function isTypedSqlDiagnosticCode(value: string): value is TypedSqlDiagnosticCode {
  return Object.hasOwn(diagnosticRegistry, value);
}
