import type { SqliteBuiltinDefinition, SqliteTableFunctionDefinition } from "./functions.js";

const unlimited = Number.POSITIVE_INFINITY;
const jsonCore = { availableSince: "3.38.0", omittedByCompileOption: "OMIT_JSON", volatility: "immutable" } as const;
const jsonb = { availableSince: "3.45.0", omittedByCompileOption: "OMIT_JSON", volatility: "immutable" } as const;

/** JSON SQL functions shipped by SQLite itself, separate from extension routines. */
export const SQLITE_JSON_FUNCTIONS: readonly SqliteBuiltinDefinition[] = Object.freeze([
  { name: "JSON", kind: "scalar", arguments: [1, 1], result: "text-nullable", ...jsonCore },
  { name: "JSON_ARRAY", kind: "scalar", arguments: [0, unlimited], result: "text", ...jsonCore },
  { name: "JSON_ARRAY_LENGTH", kind: "scalar", arguments: [1, 2], result: "integer-always-nullable", ...jsonCore },
  {
    name: "JSON_ERROR_POSITION",
    kind: "scalar",
    arguments: [1, 1],
    result: "integer-nullable",
    availableSince: "3.42.0",
    omittedByCompileOption: "OMIT_JSON",
    volatility: "immutable",
  },
  { name: "JSON_EXTRACT", kind: "scalar", arguments: [2, unlimited], result: "json-extract", ...jsonCore },
  {
    name: "JSON_INSERT",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "text-nullable",
    ...jsonCore,
  },
  {
    name: "JSON_ARRAY_INSERT",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "text-nullable",
    availableSince: "3.53.0",
    omittedByCompileOption: "OMIT_JSON",
    volatility: "immutable",
  },
  {
    name: "JSON_OBJECT",
    kind: "scalar",
    arguments: [0, unlimited],
    argumentPattern: "even",
    result: "text",
    ...jsonCore,
  },
  { name: "JSON_PATCH", kind: "scalar", arguments: [2, 2], result: "text-nullable", ...jsonCore },
  {
    name: "JSON_PRETTY",
    kind: "scalar",
    arguments: [1, 2],
    result: "text-nullable",
    availableSince: "3.46.0",
    omittedByCompileOption: "OMIT_JSON",
    volatility: "immutable",
  },
  { name: "JSON_QUOTE", kind: "scalar", arguments: [1, 1], result: "text", ...jsonCore },
  { name: "JSON_REMOVE", kind: "scalar", arguments: [1, unlimited], result: "text-nullable", ...jsonCore },
  {
    name: "JSON_REPLACE",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "text-nullable",
    ...jsonCore,
  },
  {
    name: "JSON_SET",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "text-nullable",
    ...jsonCore,
  },
  { name: "JSON_TYPE", kind: "scalar", arguments: [1, 2], result: "text-always-nullable", ...jsonCore },
  { name: "JSON_VALID", kind: "scalar", arguments: [1, 1], result: "integer-nullable", ...jsonCore },
  { name: "JSON_VALID", kind: "scalar", arguments: [2, 2], result: "integer-nullable", ...jsonb },

  { name: "JSONB", kind: "scalar", arguments: [1, 1], result: "blob-nullable", ...jsonb },
  { name: "JSONB_ARRAY", kind: "scalar", arguments: [0, unlimited], result: "blob", ...jsonb },
  { name: "JSONB_EXTRACT", kind: "scalar", arguments: [2, unlimited], result: "jsonb-extract", ...jsonb },
  {
    name: "JSONB_INSERT",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "blob-nullable",
    ...jsonb,
  },
  {
    name: "JSONB_ARRAY_INSERT",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "blob-nullable",
    availableSince: "3.53.0",
    omittedByCompileOption: "OMIT_JSON",
    volatility: "immutable",
  },
  {
    name: "JSONB_OBJECT",
    kind: "scalar",
    arguments: [0, unlimited],
    argumentPattern: "even",
    result: "blob",
    ...jsonb,
  },
  { name: "JSONB_PATCH", kind: "scalar", arguments: [2, 2], result: "blob-nullable", ...jsonb },
  { name: "JSONB_REMOVE", kind: "scalar", arguments: [1, unlimited], result: "blob-nullable", ...jsonb },
  {
    name: "JSONB_REPLACE",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "blob-nullable",
    ...jsonb,
  },
  {
    name: "JSONB_SET",
    kind: "scalar",
    arguments: [3, unlimited],
    argumentPattern: "odd",
    result: "blob-nullable",
    ...jsonb,
  },

  { name: "JSON_GROUP_ARRAY", kind: "aggregate", arguments: [1, 1], result: "text", ...jsonCore },
  { name: "JSON_GROUP_OBJECT", kind: "aggregate", arguments: [2, 2], result: "text", ...jsonCore },
  { name: "JSONB_GROUP_ARRAY", kind: "aggregate", arguments: [1, 1], result: "blob", ...jsonb },
  { name: "JSONB_GROUP_OBJECT", kind: "aggregate", arguments: [2, 2], result: "blob", ...jsonb },
]);

export const SQLITE_JSON_TABLE_FUNCTIONS: readonly SqliteTableFunctionDefinition[] = Object.freeze([
  { name: "JSON_EACH", arguments: [1, 2], result: "json", ...jsonCore },
  { name: "JSON_TREE", arguments: [1, 2], result: "json", ...jsonCore },
  {
    name: "JSONB_EACH",
    arguments: [1, 2],
    result: "jsonb",
    availableSince: "3.51.0",
    omittedByCompileOption: "OMIT_JSON",
  },
  {
    name: "JSONB_TREE",
    arguments: [1, 2],
    result: "jsonb",
    availableSince: "3.51.0",
    omittedByCompileOption: "OMIT_JSON",
  },
]);
