\set ON_ERROR_STOP on

CREATE TYPE public.account_status AS ENUM ('active', 'suspended');

CREATE DOMAIN public.email_address AS text
  CHECK (VALUE ~ '^[^@]+@[^@]+$');

CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email public.email_address NOT NULL UNIQUE,
  status public.account_status NOT NULL DEFAULT 'active',
  profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.projects (
  id uuid PRIMARY KEY,
  owner_id bigint NOT NULL REFERENCES public.users(id),
  name varchar(120) NOT NULL,
  budget numeric(14, 2),
  tags text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE public.codec_fidelity (
  id integer PRIMARY KEY,
  smallint_value smallint NOT NULL,
  integer_value integer NOT NULL,
  bigint_value bigint NOT NULL,
  numeric_value numeric(30, 10) NOT NULL,
  real_value real NOT NULL,
  double_value double precision NOT NULL,
  boolean_value boolean NOT NULL,
  text_value text NOT NULL,
  uuid_value uuid NOT NULL,
  date_value date NOT NULL,
  timestamp_value timestamp without time zone NOT NULL,
  timestamptz_value timestamp with time zone NOT NULL,
  json_value json NOT NULL,
  jsonb_value jsonb NOT NULL,
  binary_value bytea NOT NULL,
  bigint_array bigint[] NOT NULL,
  numeric_array numeric[] NOT NULL,
  text_array text[] NOT NULL,
  nullable_text text
);

CREATE VIEW public.active_users AS
SELECT id, email, created_at
FROM public.users
WHERE status = 'active';

CREATE FUNCTION public.active_user_count()
RETURNS bigint
LANGUAGE sql
STABLE
AS $$
  SELECT count(*) FROM public.users WHERE status = 'active'
$$;
