\set ON_ERROR_STOP on

CREATE TYPE public.account_status AS ENUM ('active', 'suspended');

CREATE DOMAIN public.email_address AS text
  CHECK (VALUE ~ '^[^@]+@[^@]+$');

CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email public.email_address NOT NULL UNIQUE,
  status public.account_status NOT NULL DEFAULT 'active',
  profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.projects (
  id uuid PRIMARY KEY,
  owner_id bigint NOT NULL REFERENCES public.users(id),
  name varchar(120) NOT NULL,
  budget numeric(14, 2),
  tags text[] NOT NULL DEFAULT '{}'
);

CREATE VIEW public.active_users AS
SELECT id, email, created_at
FROM public.users
WHERE status = 'active';

CREATE FUNCTION public.active_user_count()
RETURNS bigint
LANGUAGE sql
STABLE
AS $$
  SELECT count(*) FROM public.users WHERE status = 'active'
$$;
