import type { PlaygroundDialect } from "./dialect-browser-runtime.js";

export const PLAYGROUND_DIALECTS = ["postgres", "mysql", "sqlite"] as const;
export const PLAYGROUND_DIALECT_LABELS: Readonly<Record<PlaygroundDialect, string>> = Object.freeze({
  postgres: "PostgreSQL",
  mysql: "MySQL",
  sqlite: "SQLite",
});

export const DEFAULT_SCHEMAS: Readonly<Record<PlaygroundDialect, string>> = Object.freeze({
  postgres: `CREATE TYPE account_status AS ENUM ('active', 'suspended');

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  status account_status NOT NULL DEFAULT 'active',
  name text NOT NULL DEFAULT '',
  budget numeric(14, 2),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
  id bigint PRIMARY KEY,
  email text NOT NULL,
  status account_status NOT NULL,
  name text NOT NULL,
  budget numeric(14, 2)
);

CREATE TABLE account (
  id bigint PRIMARY KEY,
  email text NOT NULL,
  status account_status NOT NULL DEFAULT 'active',
  note text
);

CREATE TABLE projects (
  id bigint PRIMARY KEY,
  owner_id bigint NOT NULL REFERENCES users(id),
  name text NOT NULL,
  budget numeric(14, 2)
);`,
  mysql: `CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  status ENUM('active', 'suspended') NOT NULL DEFAULT 'active',
  name VARCHAR(120) NOT NULL DEFAULT '',
  budget DECIMAL(14, 2),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  status ENUM('active', 'suspended') NOT NULL,
  name VARCHAR(120) NOT NULL,
  budget DECIMAL(14, 2)
);

CREATE TABLE account (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  status ENUM('active', 'suspended') NOT NULL DEFAULT 'active',
  note TEXT
);

CREATE TABLE projects (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  owner_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  budget DECIMAL(14, 2)
);`,
  sqlite: `CREATE TABLE account (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('active', 'suspended')),
  name TEXT NOT NULL DEFAULT '',
  budget REAL
) STRICT;

CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL,
  status TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL
) STRICT;

CREATE TABLE projects (
  id INTEGER PRIMARY KEY,
  owner_id INTEGER NOT NULL REFERENCES account(id),
  name TEXT NOT NULL,
  budget REAL
) STRICT;`,
});

export const DEFAULT_SOURCES: Readonly<Record<PlaygroundDialect, string>> = Object.freeze({
  postgres: `import { sql } from "@typed-sql/postgres";

const accountId: bigint = 42n;

const accountById = sql\`
  SELECT account.id, account.email, account.status
  FROM users AS account
  WHERE account.id = \${accountId}
\`;`,
  mysql: `import { sql } from "@typed-sql/mysql";

const accountId: bigint = 42n;

const accountById = sql\`
  SELECT account.id, account.email, account.status
  FROM users AS account
  WHERE account.id = \${accountId}
\`;`,
  sqlite: `import { sql } from "@typed-sql/sqlite";

const accountId: bigint = 42n;

const accountById = sql\`
  SELECT account.id, account.email, account.status
  FROM account
  WHERE account.id = \${accountId}
\`;`,
});

export type { PlaygroundDialect } from "./dialect-browser-runtime.js";
